# Generated by Django 4.2.7 on 2023-12-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_model',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
