# Generated by Django 4.2.7 on 2023-12-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_job_model_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_picture', models.ImageField(null=True, upload_to='media/Profile_pic')),
            ],
        ),
    ]
