# Generated by Django 5.0 on 2023-12-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_recruiter_profile_user_generaluser_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_profile',
            name='skils',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
