# Generated by Django 5.0 on 2023-12-24 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_jobseeker_profile_skils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generaluserprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobseeker_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobseekerprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruiter_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiterprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stuff_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuffprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
