# Generated by Django 4.2.7 on 2023-12-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_generaluser_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaluser_profile',
            name='Profile_picture',
        ),
        migrations.RemoveField(
            model_name='jobseeker_profile',
            name='Profile_picture',
        ),
        migrations.RemoveField(
            model_name='recruiter_profile',
            name='Profile_picture',
        ),
        migrations.RemoveField(
            model_name='stuff_profile',
            name='Profile_picture',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='Profile_picture',
            field=models.ImageField(null=True, upload_to='media/Profile_pic'),
        ),
    ]
