# Generated by Django 5.0 on 2023-12-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_remove_generaluser_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_model',
            name='Profile_picture',
            field=models.ImageField(null=True, upload_to='media/Profile_pic'),
        ),
        migrations.AddField(
            model_name='job_model',
            name='Qualifications',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job_model',
            name='company_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job_model',
            name='deadline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
