# Generated by Django 5.0 on 2023-12-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_job_model_profile_picture_job_model_qualifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_model',
            name='Profile_picture',
        ),
        migrations.AddField(
            model_name='job_model',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to='media/Profile_Pic'),
        ),
    ]
