# Generated by Django 5.0 on 2023-12-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_remove_job_model_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_model',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
