# Generated by Django 4.2.7 on 2023-12-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_job_model_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_profile',
            name='resumes',
            field=models.ImageField(null=True, upload_to='media/resumes'),
        ),
    ]
