# Generated by Django 4.2.7 on 2023-12-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_jobseeker_profile_resumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker_profile',
            name='resumes',
            field=models.FileField(null=True, upload_to='media/resumes'),
        ),
    ]
